BEGIN;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tabs;
DROP TABLE IF EXISTS nodes;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS=1;
COMMIT;
